Before running this example please run `python run_simulations.py`

In [3]:
import glob
from itertools import product

import pandas as pd

In [4]:
GRAPHS = ['lattice', 'complete']
P = [0.5]
F = [0.1]
Q = [3, 4]
H = [0.01]

In [16]:
results = {}

for graph, p, f, q, h in product(GRAPHS, P, F, Q, H):
    current_graph_path = f"{graph}/p-{p}/f-{f}/q-{q}/h-{h}"
    current_graph_simulation = [pd.read_csv(el) for el in glob.glob(f'results/{current_graph_path}/*.csv')]
    current_graph_simulation = pd.concat(current_graph_simulation)
    results[current_graph_path] = current_graph_simulation

In [20]:
results['lattice/p-0.5/f-0.1/q-3/h-0.01']

,"(0, 0)","(0, 1)","(0, 2)","(0, 3)","(0, 4)","(0, 5)","(0, 6)","(0, 7)","(0, 8)","(0, 9)",...,"(9, 0)","(9, 1)","(9, 2)","(9, 3)","(9, 4)","(9, 5)","(9, 6)","(9, 7)","(9, 8)","(9, 9)"
0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,1,-1,-1,-1,-1
3,-1,-1,-1,-1,-1,1,1,-1,-1,-1,...,-1,-1,-1,-1,-1,1,-1,-1,-1,-1
4,-1,-1,-1,-1,-1,1,1,-1,-1,-1,...,-1,-1,-1,-1,-1,1,-1,1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,-1,-1,1,1,1,1,1,1,1,-1,...,1,1,1,1,1,-1,-1,1,1,1
997,-1,-1,1,1,-1,1,1,1,1,-1,...,1,1,1,1,1,-1,-1,1,1,1
998,-1,-1,1,1,1,1,1,1,1,-1,...,1,1,1,1,1,-1,-1,1,1,-1
999,-1,-1,1,1,1,1,1,1,1,1,...,1,-1,1,1,1,-1,-1,1,1,-1
1000,1,-1,1,1,1,1,1,1,1,1,...,1,-1,-1,1,1,-1,-1,1,1,-1